title: Static Hacker
author: Mitchell Cash
email: mitchell@mitchellcash.com
description: > # this means to ignore newlines until the next "key: value"
  This is a cool Jekyll theme, check it out!
logo: sh.gif
